#!/usr/bin/env php
<?php
declare(strict_types=1);

/**
 * phpdup phar builder.
 *
 * Produces a self-contained phpdup.phar in the project root that can be
 * dropped anywhere on PATH and run without `composer install` or a vendor/
 * directory. The phar is stamped with its version from bin/phpdup.
 *
 * Usage:
 *   php build-phar.php [--compress[=gz|bz2]]
 *
 * The resulting phar is phpdup.phar in the project root.
 * Stub boots the autoloader from within the phar, then dispatches to
 * Symfony\Console the same way bin/phpdup does, so --version / --help
 * etc. all work correctly.
 *
 * To enable phar写入, set phar.readonly=0 in php.ini, or pass:
 *   php -d phar.readonly=0 build-phar.php
 */

declare(strict_types=1);


const PHAR_NAME = 'phpdup.phar';
const STUB_NAME = 'stub.php';
const DIST_INFO = 'dist-info.json';

$opts = getopt('', ['compress::', 'out:', 'no-git']);
$compress = $opts['compress'] ?? false;
$outPath = $opts['out'] ?? __DIR__ . '/phpdup.phar';
$skipGit = isset($opts['no-git']);

// ----------------------------------------------------------------------
// 1. Bootstrap
// ----------------------------------------------------------------------
if (\Phar::running() !== '') {
    fwrite(STDERR, "build-phar: must be run from the host PHP (not from inside a phar)\n");
    exit(1);
}
if (!is_dir(__DIR__ . '/vendor') || !is_file(__DIR__ . '/vendor/autoload.php')) {
    fwrite(STDERR, "build-phar: run `composer install` before building the phar\n");
    exit(1);
}
if (ini_get('phar.readonly')) {
    fwrite(STDERR, "build-phar: phar.readonly is on — run `php -d phar.readonly=0 build-phar.php`\n");
    exit(1);
}

// ----------------------------------------------------------------------
// 2. Version — read from bin/phpdup
// ----------------------------------------------------------------------
$binContent = (string)file_get_contents(__DIR__ . '/bin/phpdup');
if (preg_match("/new Application\('phpdup',\s*'([^']+)'\)/", $binContent, $m)) {
    $version = $m[1];
} else {
    $version = '0.0.0';
}

// ----------------------------------------------------------------------
// 3. Git commit — capture now before we're inside the phar
// ----------------------------------------------------------------------
$gitCommit = $skipGit ? 'unknown' : trim((string)@exec('git rev-parse --short=8 HEAD 2>/dev/null'));
$gitBranch = $skipGit ? 'unknown' : trim((string)@exec('git rev-parse --abbrev-ref HEAD 2>/dev/null'));
$buildTime = date('c');

// ----------------------------------------------------------------------
// 4. Composer lock / installed packages for attribution
// ----------------------------------------------------------------------
$installedPackages = [];
$lockFile = __DIR__ . '/composer.lock';
if (is_file($lockFile)) {
    $lock = json_decode((string)file_get_contents($lockFile), true);
    if (isset($lock['packages'])) {
        foreach ($lock['packages'] as $pkg) {
            $installedPackages[] = [
                'name'    => $pkg['name'] ?? 'unknown',
                'version' => $pkg['version'] ?? 'unknown',
                'license' => $pkg['license'] ?? [],
            ];
        }
    }
}

// ----------------------------------------------------------------------
// 5. Build the stub
// ----------------------------------------------------------------------
$stub = <<<STUB
#!/usr/bin/env php
<?php
// phpdup phar stub — generated by build-phar.php
declare(strict_types=1);

const PHPDUP_PHAR_VERSION  = '{{VERSION}}';
const PHPDUP_PHAR_BUILT    = '{{BUILT}}';
const PHPDUP_PHAR_COMMIT   = '{{COMMIT}}';
const PHPDUP_PHAR_BRANCH   = '{{BRANCH}}';

\Phar::interceptFileFuncs();

set_error_handler(static function (int \$code, string \$msg) use (&\$error): void {
    \$error = \$msg;
});

\$error = null;
\$pharPath = \Phar::running(true);
restore_error_handler();

if (\$error !== null) {
    fwrite(STDERR, "phpdup: phar environment error: {\$error}\n");
    exit(1);
}

if (\$pharPath === '') {
    fwrite(STDERR, "phpdup: must be run from inside the phar\n");
    exit(1);
}

\$autoload = 'phar://' . \$pharPath . '/vendor/autoload.php';
if (!is_file(\$autoload)) {
    // Fallback: scan for autoload in phar root
    \$dir = new \RecursiveDirectoryIterator('phar://' . \$pharPath);
    foreach (new \RecursiveIteratorIterator(\$dir) as \$file) {
        if (\$file->getBasename() === 'autoload.php') {
            \$autoload = \$file->getPathname();
            break 2;
        }
    }
    fwrite(STDERR, "phpdup: autoload not found inside phar\n");
    exit(1);
}

require \$autoload;

use Symfony\Component\Console\Application;
use Phpdup\Cli\Command;
use Phpdup\Cli\UpdateCommand;
use Phpdup\Cli\CompletionCommand;

\$app = new Application('phpdup', PHPDUP_PHAR_VERSION);
\$app->add(new Command());
\$app->add(new UpdateCommand());
\$app->add(new CompletionCommand());
\$app->setDefaultCommand((new Command())->getName(), false);
exit(\$app->run());
STUB;

$stub = strtr($stub, [
    '{{VERSION}}' => $version,
    '{{BUILT}}'   => $buildTime,
    '{{COMMIT}}'  => $gitCommit,
    '{{BRANCH}}'  => $gitBranch,
]);

$stubFile = __DIR__ . '/' . STUB_NAME;
file_put_contents($stubFile, $stub);

// ----------------------------------------------------------------------
// 6. Create the phar
// ----------------------------------------------------------------------
if (file_exists($outPath)) {
    unlink($outPath);
}
$phar = new \Phar($outPath, 0, basename($outPath));
$phar->setSignatureAlgorithm(\Phar::SHA256);
$phar->startBuffering();

// 6a. Add autoload (vendor/)
$baseVendor = __DIR__ . '/vendor';
$autoloadFiles = [];
$iterator = new \RecursiveIteratorIterator(
    new \RecursiveDirectoryIterator($baseVendor, \FilesystemIterator::SKIP_DOTS),
    \RecursiveIteratorIterator::LEAVES_ONLY,
);

foreach ($iterator as $file) {
    if ($file->isDir() || $file->getBasename() === 'autoload.php') {
        continue;
    }
    $localPath = 'vendor/' . $iterator->getSubPathName();
    $phar->addFile($file->getPathname(), $localPath);
    if (str_ends_with($file->getBasename(), '.php')) {
        $autoloadFiles[$localPath] = true;
    }
}
$phar->addFile(__DIR__ . '/vendor/autoload.php', 'vendor/autoload.php');

// 6b. Add src/ and bin/
$phar->addFile(__DIR__ . '/bin/phpdup', 'bin/phpdup');
$srcDir = __DIR__ . '/src';
$iterator = new \RecursiveIteratorIterator(
    new \RecursiveDirectoryIterator($srcDir, \FilesystemIterator::SKIP_DOTS),
    \RecursiveIteratorIterator::LEAVES_ONLY,
);
foreach ($iterator as $file) {
    if ($file->isDir() || !str_ends_with($file->getExtension(), 'php')) {
        continue;
    }
    $localPath = 'src/' . $iterator->getSubPathName();
    $phar->addFile($file->getPathname(), $localPath);
}

// 6c. Add dist-info
$distInfo = json_encode([
    'version'   => $version,
    'built'     => $buildTime,
    'commit'    => $gitCommit,
    'branch'    => $gitBranch,
    'packages'  => $installedPackages,
], JSON_PRETTY_PRINT);
$phar->addFromString(DIST_INFO, $distInfo);

// 6d. Set stub + metadata
$phar->setStub($phar->createDefaultStub(STUB_NAME));
$phar->setMetadata([
    'version' => $version,
    'built'   => $buildTime,
    'commit'  => $gitCommit,
    'branch'  => $gitBranch,
]);
$phar->stopBuffering();

// ----------------------------------------------------------------------
// 7. Optional compression
// ----------------------------------------------------------------------
if ($compress) {
    $phar->compress(
        $compress === 'bz2' ? \Phar::BZ2 : \Phar::GZ,
    );
    $outPath .= '.' . $compress;
}

$size = filesize($outPath);
fwrite(STDOUT, sprintf(
    "build-phar: %s (%s) — version %s, commit %s\n",
    $outPath,
    number_format($size),
    $version,
    $gitCommit,
));
unlink($stubFile);

exit(0);
