#!/usr/bin/env php
<?php
// phpdup phar stub — generated by build-phar.php
declare(strict_types=1);

const PHPDUP_PHAR_VERSION  = '0.1.0';
const PHPDUP_PHAR_BUILT    = '2026-05-09T19:50:58-04:00';
const PHPDUP_PHAR_COMMIT   = 'b4386bb6';
const PHPDUP_PHAR_BRANCH   = 'master';

\Phar::interceptFileFuncs();

set_error_handler(static function (int $code, string $msg) use (&$error): void {
    $error = $msg;
});

$error = null;
$pharPath = \Phar::running(true);
restore_error_handler();

if ($error !== null) {
    fwrite(STDERR, "phpdup: phar environment error: {$error}
");
    exit(1);
}

if ($pharPath === '') {
    fwrite(STDERR, "phpdup: must be run from inside the phar
");
    exit(1);
}

$autoload = 'phar://' . $pharPath . '/vendor/autoload.php';
if (!is_file($autoload)) {
    // Fallback: scan for autoload in phar root
    $dir = new \RecursiveDirectoryIterator('phar://' . $pharPath);
    foreach (new \RecursiveIteratorIterator($dir) as $file) {
        if ($file->getBasename() === 'autoload.php') {
            $autoload = $file->getPathname();
            break 2;
        }
    }
    fwrite(STDERR, "phpdup: autoload not found inside phar
");
    exit(1);
}

require $autoload;

use Symfony\Component\Console\Application;
use Phpdup\Cli\Command;
use Phpdup\Cli\UpdateCommand;
use Phpdup\Cli\CompletionCommand;

$app = new Application('phpdup', PHPDUP_PHAR_VERSION);
$app->add(new Command());
$app->add(new UpdateCommand());
$app->add(new CompletionCommand());
$app->setDefaultCommand((new Command())->getName(), false);
exit($app->run());