<?php
declare(strict_types=1);

namespace Phpdup\Testing;

/**
 * Pure markdown renderer for benchmark results.
 *
 * Inputs are simple arrays so the renderer is unit-testable without
 * spinning up the full bench pipeline. The bench harness
 * (`bench/run.php`) hydrates these arrays from real tool runs; the
 * tests under `tests/Unit/Bench/` construct synthetic inputs.
 */
final class BenchmarkResultsRenderer
{
    /**
     * Render the per-corpus, per-tool comparison table.
     *
     * @param list<array{
     *     corpus: string,
     *     files: int|null,
     *     tool: string,
     *     wall_s: float|null,
     *     peak_mb: float|null,
     *     clusters: int|null,
     *     extra: array<string, mixed>
     * }> $rows
     */
    public function renderRunMarkdown(array $rows, string $title = 'Comparative benchmark'): string
    {
        $out  = "# {$title}\n\n";
        $out .= 'Generated: ' . gmdate('Y-m-d H:i:s') . " UTC\n\n";
        if ($rows === []) {
            return $out . "_(no results)_\n";
        }
        // Group by corpus.
        $byCorpus = [];
        foreach ($rows as $r) {
            $byCorpus[$r['corpus']][] = $r;
        }
        foreach ($byCorpus as $corpus => $group) {
            $files = $group[0]['files'] ?? null;
            $out .= "## Corpus: `{$corpus}`";
            if ($files !== null) {
                $out .= " (" . $files . " PHP files)";
            }
            $out .= "\n\n";
            $out .= "| Tool | Wall (s) | Peak RSS (MB) | Clusters | Notes |\n";
            $out .= "|------|---------:|--------------:|---------:|-------|\n";
            foreach ($group as $r) {
                $extra = [];
                foreach ($r['extra'] as $k => $v) {
                    if ($v === null || $v === '' || is_array($v) || is_object($v)) {
                        continue;
                    }
                    $extra[] = "{$k}={$v}";
                }
                $note = $extra === [] ? '—' : implode(', ', $extra);
                $out .= sprintf(
                    "| %s | %s | %s | %s | %s |\n",
                    $r['tool'],
                    $this->fmt($r['wall_s'], '%.2f'),
                    $this->fmt($r['peak_mb'], '%.1f'),
                    $r['clusters'] === null ? '—' : (string)$r['clusters'],
                    $note,
                );
            }
            $out .= "\n";
        }
        return $out;
    }

    /**
     * Render the precision/recall table for the synthetic-corpus
     * detection-rate scoring.
     *
     * @param list<array{
     *     tool: string,
     *     precision: float,
     *     recall: float,
     *     f1: float,
     *     tp: int,
     *     fp: int,
     *     fn: int,
     *     reported: int,
     *     ground_truth: int
     * }> $scores
     */
    public function renderDetectionRateMarkdown(array $scores): string
    {
        $out  = "# Detection-rate scoring\n\n";
        $out .= "Synthetic corpus generated by `Phpdup\\Testing\\FuzzCorpusGenerator`.\n";
        $out .= "Two clusters match when their member-set Jaccard ≥ "
              . BenchmarkScoreCalculator::OVERLAP_FLOOR
              . " (line-range tolerance ±" . BenchmarkScoreCalculator::LINE_TOLERANCE . ").\n\n";
        if ($scores === []) {
            return $out . "_(no scores; tool runs unavailable)_\n";
        }
        $out .= "| Tool | Precision | Recall | F1 | TP | FP | FN | Reported | Ground truth |\n";
        $out .= "|------|----------:|-------:|---:|---:|---:|---:|---------:|-------------:|\n";
        foreach ($scores as $s) {
            $out .= sprintf(
                "| %s | %.2f | %.2f | %.2f | %d | %d | %d | %d | %d |\n",
                $s['tool'],
                $s['precision'],
                $s['recall'],
                $s['f1'],
                $s['tp'],
                $s['fp'],
                $s['fn'],
                $s['reported'],
                $s['ground_truth'],
            );
        }
        return $out;
    }

    private function fmt(?float $v, string $fmt): string
    {
        return $v === null ? '—' : sprintf($fmt, $v);
    }
}
