<?php
declare(strict_types=1);

namespace Phpdup\Reporting;

use Phpdup\Clustering\Cluster;
use Phpdup\Refactor\Hole;

/**
 * Generates PHPUnit test skeletons for the suggested abstraction.
 *
 * Produces one test class per cluster with a data-provider that
 * iterates the holes' observed values across cluster members. The
 * test bodies are intentionally `markTestIncomplete()` placeholders
 * — a human still needs to fill in the expected behaviour, but the
 * scaffolding (provider rows + signature + naming) is done.
 */
final class RefactorTestReporter
{
    /**
     * Write one PHPUnit test-skeleton file per cluster under `$dir`.
     */
    public function writeTo(Report $report, string $dir): void
    {
        if ($dir !== '' && !is_dir($dir)) {
            @mkdir($dir, 0o775, true);
        }
        foreach ($report->clusters as $cluster) {
            if (count($cluster->members) < 2) {
                continue;
            }
            $safeId = preg_replace('/[^a-zA-Z0-9_-]/', '_', $cluster->id);
            $file = $dir . DIRECTORY_SEPARATOR . "Cluster{$safeId}Test.php";
            file_put_contents($file, $this->buildTest($cluster));
        }
    }

    /**
     * Render the test-class source for one cluster.
     */
    public function buildTest(Cluster $cluster): string
    {
        $className = "Cluster{$cluster->id}Test";
        $paramList = $this->generateParamList($cluster->holes);
        $rows = $this->providerRows($cluster);
        $providerBody = '';
        foreach ($rows as $label => $args) {
            $providerBody .= "        '" . addslashes($label) . "' => [" . implode(', ', $args) . "],\n";
        }

        return <<<PHP
<?php
declare(strict_types=1);

namespace Refactored\\Tests;

use PHPUnit\\Framework\\TestCase;

/**
 * Auto-generated by phpdup for cluster {$cluster->id}.
 *
 * The data-provider rows mirror the holes observed across cluster members.
 * Fill in each test body with the expected return value (or behaviour) for
 * the corresponding inputs — until then it is a markTestIncomplete().
 */
final class {$className} extends TestCase
{
    /**
     * @dataProvider casesProvider
     */
    public function testAbstractionMatchesEachMember({$paramList}): void
    {
        \$this->markTestIncomplete('phpdup: fill in expected output for the abstraction');
    }

    /** @return array<string, array<int, mixed>> */
    public static function casesProvider(): array
    {
        return [
{$providerBody}        ];
    }
}

PHP;
    }

    /**
     * Generate parameter list string from holes for the test method signature.
     *
     * @param list<Hole> $holes
     */
    private function generateParamList(array $holes): string
    {
        if ($holes === []) {
            return '';
        }
        $params = [];
        foreach ($holes as $h) {
            $name = $h->suggestedName !== '' ? $h->suggestedName : $h->placeholder;
            $type = $h->inferredType !== '' ? $h->inferredType : 'mixed';
            $params[] = "{$type} \${$name}";
        }
        return implode(', ', $params);
    }

    /**
     * @return array<string, list<string>> label → list of repr() strings
     *                                     (one per hole, taken from the
     *                                     member's observed value).
     */
    private function providerRows(Cluster $cluster): array
    {
        $count = count($cluster->members);
        $out = [];
        for ($i = 0; $i < $count; $i++) {
            $row = [];
            foreach ($cluster->holes as $h) {
                $row[] = $this->reprValue($h, $i);
            }
            $label = "member_{$i}_" . str_replace([':', '/'], '_', $cluster->members[$i]->location());
            $out[$label] = $row;
        }
        return $out;
    }

    /**
     * Render one observed hole value as a PHP literal suitable for
     * embedding directly in a `casesProvider` row.
     */
    private function reprValue(Hole $h, int $memberIdx): string
    {
        $v = $h->observedValues[$memberIdx] ?? null;
        if ($v === null || $v === '<absent>') {
            return $h->kind === 'optional_block' ? 'false' : 'null';
        }
        // Numeric → bare; bool/null keywords → bare; otherwise quoted string.
        if (preg_match('/^-?\d+(\.\d+)?$/', $v) === 1) {
            return $v;
        }
        if (in_array($v, ['true', 'false', 'null'], true)) {
            return $v;
        }
        if (preg_match('/^([\'"]).*\1$/s', $v) === 1) {
            return $v;
        }
        // Anything else → quote as a PHP string for the provider row.
        return "'" . addslashes($v) . "'";
    }
}
